DECLARE 
    V_VAR_1         VARCHAR2(10) :='abc';
    V_ERROR_1     VARCHAR2(4000);
    V_VAR_3          VARCHAR2(10):='10';
     V_ERROR_1     VARCHAR2(4000);	 
BEGIN 
DBMS_OUTPUT.PUT_LINE('VALOR DE 5*2 :'||(5*2));
DBMS_OUTPUT.PUT_LINE('VALOR DE 5**2:' ||(5**2));

IF(5=5) THEN
     DBMS_OUTPUT.PUT_LINE('5 ES IGUAK A 5');
END IF;

IF (5!=4 OR 5<>3 OR 5~=7)THEN 
    DBMS_OUTPUT.PUT_LINE('5 ES DIFERENTE DE 4,3 Y 7');
END IF ;
IF (V_VAR_2 LIKE '%MARIA%') THEN 
    DBMS_OUTPUT.PUT_LINE('LA VARIABLE V_VAR_2 TIENE EL VALOR  LIKE MARIA');
END IF;
IF (V_VAR_2 LIKE '%PEDRO%') THEN 
    DBMS_OUTPUT.PUT_LINE(' LA VARIABLE V_VAR_2 QUE CONTIEN PEDRO'):
END IF;
IF(V_VAR_# IN ('10','20','30','40')) THEN 
    DBMS_OUTPUT.PUT_LINE('LA VARIABLE ELSE IF PUEDER SER EL 10,20,30,40')
END IF 
	




























